// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/food.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FoodOrderService_GetMenu_FullMethodName = "/foodorder.FoodOrderService/GetMenu"
)

// FoodOrderServiceClient is the client API for FoodOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type FoodOrderServiceClient interface {
	GetMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*MenuResponse, error)
}

type foodOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodOrderServiceClient(cc grpc.ClientConnInterface) FoodOrderServiceClient {
	return &foodOrderServiceClient{cc}
}

func (c *foodOrderServiceClient) GetMenu(ctx context.Context, in *MenuRequest, opts ...grpc.CallOption) (*MenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuResponse)
	err := c.cc.Invoke(ctx, FoodOrderService_GetMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodOrderServiceServer is the server API for FoodOrderService service.
// All implementations must embed UnimplementedFoodOrderServiceServer
// for forward compatibility.
//
// Service definition
type FoodOrderServiceServer interface {
	GetMenu(context.Context, *MenuRequest) (*MenuResponse, error)
	mustEmbedUnimplementedFoodOrderServiceServer()
}

// UnimplementedFoodOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFoodOrderServiceServer struct{}

func (UnimplementedFoodOrderServiceServer) GetMenu(context.Context, *MenuRequest) (*MenuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMenu not implemented")
}
func (UnimplementedFoodOrderServiceServer) mustEmbedUnimplementedFoodOrderServiceServer() {}
func (UnimplementedFoodOrderServiceServer) testEmbeddedByValue()                          {}

// UnsafeFoodOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoodOrderServiceServer will
// result in compilation errors.
type UnsafeFoodOrderServiceServer interface {
	mustEmbedUnimplementedFoodOrderServiceServer()
}

func RegisterFoodOrderServiceServer(s grpc.ServiceRegistrar, srv FoodOrderServiceServer) {
	// If the following call pancis, it indicates UnimplementedFoodOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FoodOrderService_ServiceDesc, srv)
}

func _FoodOrderService_GetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodOrderServiceServer).GetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoodOrderService_GetMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodOrderServiceServer).GetMenu(ctx, req.(*MenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FoodOrderService_ServiceDesc is the grpc.ServiceDesc for FoodOrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FoodOrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foodorder.FoodOrderService",
	HandlerType: (*FoodOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMenu",
			Handler:    _FoodOrderService_GetMenu_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/food.proto",
}
